---
- name: Welcome message
  hosts: all
  gather_facts: true

  tasks:
    - name: Print welcome message
      ansible.builtin.debug:
        msg: "Welcome to the Ansible Automation Platform dashboard {{ ansible_hostname }}!"
